export const POST_EMAIL_REQUEST = "POST_EMAIL_REQUEST"
export const POST_EMAIL_SUCCESS = "POST_EMAIL_SUCCESS"
export const POST_EMAIL_FAILURE = "POST_EMAIL_FAILURE"

export const VERIFY_OTP_REQUEST = "VERIFY_OTP_REQUEST"
export const VERIFY_OTP_SUCCESS = "VERIFY_OTP_SUCCESS"
export const VERIFY_OTP_FAILURE = "VERIFY_OTP_FAILURE"

export const FETCH_EXPENSE_REQUEST = "FETCH_EXPENSE_REQUEST"
export const FETCH_EXPENSE_SUCCESS = "FETCH_EXPENSE_SUCCESS"
export const FETCH_EXPENSE_FAILURE = "FETCH_EXPENSE_FAILURE"

export const FETCH_PAGINATION_EXPENSE_REQUEST = "FETCH_PAGINATION_EXPENSE_REQUEST"
export const FETCH_PAGINATION_EXPENSE_SUCCESS = "FETCH_PAGINATION_EXPENSE_SUCCESS"
export const FETCH_PAGINATION_EXPENSE_FAILURE = "FETCH_PAGINATION_EXPENSE_FAILURE"