export const ONLY_EXPENSE_REQUEST = "ONLY_EXPENSE_REQUEST";
export const ONLY_EXPENSE_SUCCESS = "ONLY_EXPENSE_SUCCESS";
export const ONLY_EXPENSE_FAILURE = "ONLY_EXPENSE_FAILURE";

export const ONLY_EXPENSE_PAGINATION_REQUEST = "ONLY_EXPENSE_PAGINATION_REQUEST";
export const ONLY_EXPENSE_PAGINATION_SUCCESS = "ONLY_EXPENSE_PAGINATION_SUCCESS";
export const ONLY_EXPENSE_PAGINATION_FAILURE = "ONLY_EXPENSE_PAGINATION_FAILURE";

export const ONLY_EXPENSE_POST_REQUEST = "ONLY_EXPENSE_POST_REQUEST";
export const ONLY_EXPENSE_POST_SUCCESS = "ONLY_EXPENSE_POST_SUCCESS";
export const ONLY_EXPENSE_POST_FAILURE = "ONLY_EXPENSE_POST_FAILURE";

export const ONLY_EXPENSE_PATCH_REQUEST = "ONLY_EXPENSE_PATCH_REQUEST";
export const ONLY_EXPENSE_PATCH_SUCCESS = "ONLY_EXPENSE_PATCH_SUCCESS";
export const ONLY_EXPENSE_PATCH_FAILURE = "ONLY_EXPENSE_PATCH_FAILURE";

export const ONLY_EXPENSE_DELETE_REQUEST = "ONLY_EXPENSE_DELETE_REQUEST";
export const ONLY_EXPENSE_DELETE_SUCCESS = "ONLY_EXPENSE_DELETE_SUCCESS";
export const ONLY_EXPENSE_DELETE_FAILURE = "ONLY_EXPENSE_DELETE_FAILURE";
