export const ROOM_MATES_REQUEST = "ROOM_MATES_REQUEST";
export const ROOM_MATES_SUCCESS = "ROOM_MATES_SUCCESS";
export const ROOM_MATES_FAILURE = "ROOM_MATES_FAILURE";

export const ROOM_MATES_PAGINATION_REQUEST = "ROOM_MATES_PAGINATION_REQUEST";
export const ROOM_MATES_PAGINATION_SUCCESS = "ROOM_MATES_PAGINATION_SUCCESS";
export const ROOM_MATES_PAGINATION_FAILURE = "ROOM_MATES_PAGINATION_FAILURE";

export const ROOM_MATES_POST_REQUEST = "ROOM_MATES_POST_REQUEST";
export const ROOM_MATES_POST_SUCCESS = "ROOM_MATES_POST_SUCCESS";
export const ROOM_MATES_POST_FAILURE = "ROOM_MATES_POST_FAILURE";

export const ROOM_MATES_PATCH_REQUEST = "ROOM_MATES_PATCH_REQUEST";
export const ROOM_MATES_PATCH_SUCCESS = "ROOM_MATES_PATCH_SUCCESS";
export const ROOM_MATES_PATCH_FAILURE = "ROOM_MATES_PATCH_FAILURE";

export const ROOM_MATES_DELETE_REQUEST = "ROOM_MATES_DELETE_REQUEST";
export const ROOM_MATES_DELETE_SUCCESS = "ROOM_MATES_DELETE_SUCCESS";
export const ROOM_MATES_DELETE_FAILURE = "ROOM_MATES_DELETE_FAILURE";
